### ISSUE TITLE
error while loading shared libraries: libftdi.so.1

### ISSUE THREAD

**Issue by lancew** [keyboardio/Kaleidoscope-Docker#4]
After building the firmware with `bin/builder -s https://github.com/keyboardio/Model01-Firmware.git`

Then try
`$ bin/flasher Model01`

Which produced:
`When ready, hold down PROG, and press ENTER. Keep holding PROG until flashing starts...`

I did this and after a short time (0.5 of a second to a second maybe) I got this message:

`output/tools/avrdude: error while loading shared libraries: libftdi.so.1: cannot open shared object file: No such file or directory
`

Keyboard then sat wit the prog button light on, nothing happens, unpllugging and plugging keyboard back in brought keyboard back to use.

I'm on ArchLinux, Gnome. Please ask me anything you might need to know.

**Comment by lancew** [comment]
Perhaps related issue?
When trying the build command from the travis file I get the following:

`
$ bin/builder -s https://github.com/keyboardio/Model01-Firmware.git -O plugin-v2
Building output/Model01-Firmware/Model01-Firmware (0.0.0-gv1.22-25-g29c8) ...
In file included from /src/firmware/sketch/Model01-Firmware.ino:17:0:
/src/firmware/hardware/keyboardio/avr/libraries/Kaleidoscope/src/Kaleidoscope.h: In member function 'void kaleidoscope::Kaleidoscope_::use(...)':
/src/firmware/hardware/keyboardio/avr/libraries/Kaleidoscope/src/Kaleidoscope.h:146:5: error: static assertion failed: 
------------------------------------------------------------------------
Your sketch uses Kaleidoscope.use(), an old-style API to initialize
plugins. To fix this, you need to modify your .ino sketch file, and
replacing the text "Kaleidoscope.use" with "KALEIDOSCOPE_INIT_PLUGINS",
then remove the & from all of the plugins inside it, and finally, move
it outside of "setup()":

If your current sketch looks like this: 
  void setup() {
    Kaleidoscope.use(&Plugin1, &Plugin2);
    Kaleidoscope.setup();
  }

You should change it so that it looks like this:
  KALEIDOSCOPE_INIT_PLUGINS(Plugin1, Plugin2);
  void setup() {
    Kaleidoscope.setup();
  }

If this error doesn't make sense to you or you have any trouble, please
send a copy of your .ino sketch file to help@keyboard.io and we can
help fix it.
------------------------------------------------------------------------

     static_assert(false, _DEPRECATE(_DEPRECATED_MESSAGE_USE));
     ^
exit status 1
`

**Comment by algernon** [comment]
> `output/tools/avrdude: error while loading shared libraries: libftdi.so.1: cannot open shared object file: No such file or directory`

Yeah, this part of the process is a little fragile. At the moment, you need a few libraries on the host so that the `avrdude` command will be able to work. Eventually, I'll either ship a static version, or copy the libs out too.

For the time being, if you can install the `avrdude` package, that will fix this issue. It's unrelated to the other one, by the way.

**Comment by algernon** [comment]
> Perhaps related issue?

No, it is unrelated, see keyboardio/Kaleidoscope#346. For the time being, until that fix gets merged, don't use `-O plugin-v2`. Not sure why the current code fails in some cases, but works in others... the new code should work every time though.

**Comment by lancew** [comment]
OK, so I changed in bin/flasher `output/tools/avrdude`  to `avrdude` and was able to run it and update the keyboard! Thanks for help
